# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: satoshi-unit 0.1.9 ruby lib

Gem::Specification.new do |s|
  s.name = "satoshiproc-unit"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roman Snitko", "Oscar Guindzberg"]
  s.date = "2017-06-18"
  s.description = "Converts various proc denominations in Satoshiprocs and back"
  s.email = "oscar.guindzberg@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/satoshiproc-unit.rb",
    "lib/satoshiproc.rb",
    "satoshiproc-unit.gemspec",
    "spec/satoshiproc_spec.rb"
  ]
  s.homepage = "http://github.com/oscarguindzberg/satoshiproc-unit"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Converts various proc denominations in Satoshiprocs and back"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.1.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.1.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.1.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

